version: '3'
services:
  db:
    image: postgres:13.1
    environment: 
      POSTGRES_PASSWORD: "localdev"
      POSTGRES_USER: "vespa"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"