version: '3'
services:
  db:
    image: postgres:13.1
    environment: 
      POSTGRES_PASSWORD: "localdev"
      POSTGRES_USER: "vespa"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3
    environment: 
      RABBITMQ_DEFAULT_VHOST: "vespa"
  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
  celery:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: bash ./start_worker.sh